# Travis CI configuration
language: php
php:
  - '7.0'
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - composer dump-autoload
script:
  - vendor/bin/phpunit
addons:
    code_climate:
        repo_token: f7c8f7e557e96a393cd1b5a4842f354283b1d69844db8bdc5b259826a2fa2414